os: linux
services:
- docker
sudo: required
language: python
env:
  global:
  - CONAN_UPLOAD=1
  - CONAN_REFERENCE="cucumber-cpp/master"
  - CONAN_USERNAME="meshell"
  - CONAN_CHANNEL="testing"
  - CONAN_TOTAL_PAGES=1
  - CONAN_CURRENT_PAGE=1
  - CONAN_STABLE_BRANCH_PATTERN="release/*"
  - secure: D8Rx6ScqG2G6qzO016bvTDpk3VSrJtgPDSp17HOWIu0TCjPia8Y63WaVcB5eFxLqu5TJ4lYiEWlBxxd47gP+eVXtf/Y92HK4VlV67gcd2vRCVBP1a1opF0Mo8PdR/Pi2Dbofz2rWM/bk3cOVKEih0EU07F1rrHPZVTBNwPNk0DMyLTmjXZdW0wPbYUMSOWu4sNrl3OefOkSRrQ9NWtn+eW8x5Tw3b9Q5eN1TNLiqr7OU1ChgtZsIhhrPnGh5JiuqhV63f7Lt62f6dmposPJn0JWx6VrUSduPe2c7IQ9jxxwJh915thgdVu18FLaercu1hUiQat1oC5fO+mo7BNnYcd9C8OfDRhkNzUtRS1GFbSVs9Sam77HNQe4dB6v07g72GFcKmR11qpOpYVFCNODsiMMtHScCkMNSWoFdzEHAnkmYIlMvy6S2DBgVS+d+DhRVIYRIJ9QL7q8o/ZaJd/mplQ/VA+Lil9BNdLTbG4cTo7zuwofF89pE/a7MpydnBx6QuGwmeRQjfK3+AObjUsPMXvKxzFhJMlsMv1cVqAWKK8DtuOnyiNYY0QhPu6GVo5ft6zVppV0h67OcqPirh5ROnnERSW0mOi3ZbbwIEjgYs5TEAMOlgYLtgRbmLYgyNkc2jXyPq2KaIAKqGaCt6OkeYdLyudr3Q+30EEVEScdQt4M=
  matrix:
  - CONAN_GCC_VERSIONS=4.6 CONAN_USE_DOCKER=1
  - CONAN_GCC_VERSIONS=4.8 CONAN_USE_DOCKER=1
  - CONAN_GCC_VERSIONS=4.9 CONAN_USE_DOCKER=1
  - CONAN_GCC_VERSIONS=5.2 CONAN_USE_DOCKER=1
  - CONAN_GCC_VERSIONS=5.3 CONAN_USE_DOCKER=1
  - CONAN_GCC_VERSIONS=5.4 CONAN_USE_DOCKER=1
  - CONAN_GCC_VERSIONS=6.2 CONAN_USE_DOCKER=1
matrix:
  include:
  - os: osx
    osx_image: xcode8
    language: generic
    env:
  - os: osx
    osx_image: xcode7.3
    language: generic
    env:
  - os: osx
    osx_image: xcode7.1
    language: generic
    env:
  - os: osx
    osx_image: xcode6.4
    language: generic
    env:
  - os: osx
    osx_image: xcode6.2
    language: generic
    env:
notifications:
  email:
    recipients:
    - estermann.michel@gmail.com
    on_success: change
    on_failure: always
install:
- "./.travis/install.sh"
script:
- "./.travis/run.sh"
