os: linux

services:
- docker

sudo: required

language: python

env:
  global:
    - CONAN_UPLOAD=1
    - CONAN_REFERENCE="cucumber-cpp/master"
    - CONAN_CHANNEL="stable"
    - CONAN_TOTAL_PAGES=4
    - CONAN_STABLE_BRANCH_PATTERN="release/*"
  matrix:
      - CONAN_GCC_VERSIONS=4.6 CONAN_CURRENT_PAGE=1 CONAN_USE_DOCKER=1 CONAN_DOCKER_IMAGE=meshell/conangcc46
      - CONAN_GCC_VERSIONS=4.6 CONAN_CURRENT_PAGE=2 CONAN_USE_DOCKER=1 CONAN_DOCKER_IMAGE=meshell/conangcc46
      - CONAN_GCC_VERSIONS=4.6 CONAN_CURRENT_PAGE=3 CONAN_USE_DOCKER=1 CONAN_DOCKER_IMAGE=meshell/conangcc46
      - CONAN_GCC_VERSIONS=4.6 CONAN_CURRENT_PAGE=4 CONAN_USE_DOCKER=1 CONAN_DOCKER_IMAGE=meshell/conangcc46

      - CONAN_GCC_VERSIONS=4.8 CONAN_CURRENT_PAGE=1 CONAN_USE_DOCKER=1 CONAN_DOCKER_IMAGE=meshell/conangcc48
      - CONAN_GCC_VERSIONS=4.8 CONAN_CURRENT_PAGE=2 CONAN_USE_DOCKER=1 CONAN_DOCKER_IMAGE=meshell/conangcc48
      - CONAN_GCC_VERSIONS=4.8 CONAN_CURRENT_PAGE=3 CONAN_USE_DOCKER=1 CONAN_DOCKER_IMAGE=meshell/conangcc48
      - CONAN_GCC_VERSIONS=4.8 CONAN_CURRENT_PAGE=4 CONAN_USE_DOCKER=1 CONAN_DOCKER_IMAGE=meshell/conangcc48

      - CONAN_GCC_VERSIONS=4.9 CONAN_CURRENT_PAGE=1 CONAN_USE_DOCKER=1 CONAN_DOCKER_IMAGE=meshell/conangcc49
      - CONAN_GCC_VERSIONS=4.9 CONAN_CURRENT_PAGE=2 CONAN_USE_DOCKER=1 CONAN_DOCKER_IMAGE=meshell/conangcc49
      - CONAN_GCC_VERSIONS=4.9 CONAN_CURRENT_PAGE=3 CONAN_USE_DOCKER=1 CONAN_DOCKER_IMAGE=meshell/conangcc49
      - CONAN_GCC_VERSIONS=4.9 CONAN_CURRENT_PAGE=4 CONAN_USE_DOCKER=1 CONAN_DOCKER_IMAGE=meshell/conangcc49

      - CONAN_GCC_VERSIONS=5.2 CONAN_CURRENT_PAGE=1 CONAN_USE_DOCKER=1 CONAN_DOCKER_IMAGE=meshell/conangcc52
      - CONAN_GCC_VERSIONS=5.2 CONAN_CURRENT_PAGE=2 CONAN_USE_DOCKER=1 CONAN_DOCKER_IMAGE=meshell/conangcc52
      - CONAN_GCC_VERSIONS=5.2 CONAN_CURRENT_PAGE=3 CONAN_USE_DOCKER=1 CONAN_DOCKER_IMAGE=meshell/conangcc52
      - CONAN_GCC_VERSIONS=5.2 CONAN_CURRENT_PAGE=4 CONAN_USE_DOCKER=1 CONAN_DOCKER_IMAGE=meshell/conangcc52

      - CONAN_GCC_VERSIONS=5.3 CONAN_CURRENT_PAGE=1 CONAN_USE_DOCKER=1 CONAN_DOCKER_IMAGE=meshell/conangcc53
      - CONAN_GCC_VERSIONS=5.3 CONAN_CURRENT_PAGE=2 CONAN_USE_DOCKER=1 CONAN_DOCKER_IMAGE=meshell/conangcc53
      - CONAN_GCC_VERSIONS=5.3 CONAN_CURRENT_PAGE=3 CONAN_USE_DOCKER=1 CONAN_DOCKER_IMAGE=meshell/conangcc53
      - CONAN_GCC_VERSIONS=5.3 CONAN_CURRENT_PAGE=4 CONAN_USE_DOCKER=1 CONAN_DOCKER_IMAGE=meshell/conangcc53

      - CONAN_GCC_VERSIONS=5.4 CONAN_CURRENT_PAGE=1 CONAN_USE_DOCKER=1 CONAN_DOCKER_IMAGE=meshell/conangcc54
      - CONAN_GCC_VERSIONS=5.4 CONAN_CURRENT_PAGE=2 CONAN_USE_DOCKER=1 CONAN_DOCKER_IMAGE=meshell/conangcc54
      - CONAN_GCC_VERSIONS=5.4 CONAN_CURRENT_PAGE=3 CONAN_USE_DOCKER=1 CONAN_DOCKER_IMAGE=meshell/conangcc54
      - CONAN_GCC_VERSIONS=5.4 CONAN_CURRENT_PAGE=4 CONAN_USE_DOCKER=1 CONAN_DOCKER_IMAGE=meshell/conangcc54

      - CONAN_GCC_VERSIONS=6.2 CONAN_CURRENT_PAGE=1 CONAN_USE_DOCKER=1 CONAN_DOCKER_IMAGE=meshell/conangcc62
      - CONAN_GCC_VERSIONS=6.2 CONAN_CURRENT_PAGE=2 CONAN_USE_DOCKER=1 CONAN_DOCKER_IMAGE=meshell/conangcc62
      - CONAN_GCC_VERSIONS=6.2 CONAN_CURRENT_PAGE=3 CONAN_USE_DOCKER=1 CONAN_DOCKER_IMAGE=meshell/conangcc62
      - CONAN_GCC_VERSIONS=6.2 CONAN_CURRENT_PAGE=4 CONAN_USE_DOCKER=1 CONAN_DOCKER_IMAGE=meshell/conangcc62

      - CONAN_GCC_VERSIONS=6.3 CONAN_CURRENT_PAGE=1 CONAN_USE_DOCKER=1 CONAN_DOCKER_IMAGE=meshell/conangcc63
      - CONAN_GCC_VERSIONS=6.3 CONAN_CURRENT_PAGE=2 CONAN_USE_DOCKER=1 CONAN_DOCKER_IMAGE=meshell/conangcc63
      - CONAN_GCC_VERSIONS=6.3 CONAN_CURRENT_PAGE=3 CONAN_USE_DOCKER=1 CONAN_DOCKER_IMAGE=meshell/conangcc63
      - CONAN_GCC_VERSIONS=6.3 CONAN_CURRENT_PAGE=4 CONAN_USE_DOCKER=1 CONAN_DOCKER_IMAGE=meshell/conangcc63

matrix:
  include:
  - os: osx
    osx_image: xcode8
    language: generic
    env:
  - os: osx
    osx_image: xcode7.3
    language: generic
    env:
  - os: osx
    osx_image: xcode7.1
    language: generic
    env:
  - os: osx
    osx_image: xcode6.4
    language: generic
    env:
  - os: osx
    osx_image: xcode6.2
    language: generic
    env:
notifications:
  email:
    recipients:
    - estermann.michel@gmail.com
    on_success: change
    on_failure: always
install:
- "./.travis/install.sh"
script:
- "./.travis/run.sh"
